version: '3.3'

services:
  server:
    build: ./api
    restart: always
    ports: 
      - "8080:8080"
    volumes: 
      - ./api:/api
      - /api/node_modules
    depends_on: 
      - mongodb
    networks:
      - webappnetwork
  client_web:
    build: ./web
    restart: always
    ports:
    - 8081:8081
    # depends_on:
    #   - client_mobile
    #   - server
    volumes:
    - ./web:/web
    - /web/node_modules
    - apk:/web/public/client_apk_final/:ro
    networks:
      - webappnetwork
  # client_mobile:
  #   build: ./mobile
  #   volumes:
  #   - ./mobile:/mobile
  #   - /mobile/node_modules
  #   - apk:/mobile/android/app/build/outputs/apk/release/:rw
  #   networks:
  #     - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes: 
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks: 
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes:
  apk: