version: '3.7'

services:
  api:
    build: ./api
    restart: always
    ports: 
      - "8080:8080"
    volumes: 
      - ./api:/api
      - /api/node_modules
    depends_on: 
      - mongodb
    networks:
      - webappnetwork
  client_web:
    build: ./web
    restart: always
    ports:
    - 8081:8081
    volumes:
    - ./web:/web
    - /web/node_modules
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes: 
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks: 
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
